# app/target_headers.py
TARGET_HEADERS = [
    "AIS_DKR_ID","ASU_ODS_ID","UDS_count_in_object","District","Region","Coordinates",
    "State_program","Object_category","INN_OIV_GRBS","OIV_GRBS","INN_state_customer",
    "State_customer","Object_name","Object_status_on_report_date","Discussion_with_residents",
    "Measurement_unit","Indicator_volume_unit","Expertise_status_PIR","Planned_auction_date_PIR",
    "Actual_auction_date_PIR","Planned_contract_date_PIR","Actual_contract_date_PIR",
    "INN_project_organization","Project_organization_name","PSD_development_period",
    "Expertise_status_SMR","Planned_review_date_Pre_MRG","Actual_review_date_Pre_MRG",
    "Planned_review_date_MRG","Actual_review_date_MRG","Planned_auction_date_SMR",
    "Actual_auction_date_SMR","Planned_contract_date_SMR","Actual_contract_date_SMR",
    "Work_cost_million_rub","Paid_work_cost_million_rub","Planned_start_date_SMR",
    "Planned_end_date_SMR","Actual_start_date_SMR","Actual_end_date_SMR","Contract_end_date",
    "INN_contractor","Contractor","Object_readiness_percentage","State_commission_approval_date",
    "Last_work_year","Start_work_year","Current_work_year","KBK","Workers_count","Machinery_count",
    "Penalty_cost_million_rub","Building_repair_area_sq_m","Road_repair_area_UDS_sq_m",
    "Other_road_repair_area_sq_m","Soft_covering_area_sq_m","Granite_paving_area_sq_m",
    "Concrete_paving_area_sq_m","Granite_bordure_area_m","Concrete_bordure_area_m",
    "Lawn_area_sq_m","Tree_planting_count","Bush_planting_count","MAF_installation_count",
    "Lighting_pole_installation_count","Storm_water_network_development_m",
    "Cable_channel_installation_m","Public_transport_stop_count","Bicycle_parking_count",
    "Navigation_stellas_count","Demolition_work_volume_cubic_m","Floor_screed_area_sq_m",
    "Interior_finishing_area_sq_m","Ventilation_system_installation_m",
    "Electrical_panel_installation_count","Water_supply_system_installation_count",
    "Heating_system_installation_count","AC_unit_installation_count",
    "Surveillance_system_installation_count","Fence_installation_m",
    "Barrier_installation_count","Parking_space_installation_count","Lift_platform_installation_count",
]
